name: NuGet Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'

      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build the project
        run: dotnet build --configuration Release --no-restore
        
      - name: Run tests
        run: dotnet test --no-restore --verbosity normal
        
      - name: Pack NuGet Package
        run: dotnet pack --configuration Release --no-build --output ./nupkg
        
      - name: Publish to GitHub Packages
        run: dotnet nuget push ./nupkg/*.nupkg --source "https://nuget.pkg.github.com/NNT-ADevStudio/index.json" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
